# Site wide configuration

title: Geoffrey Pruvost
locale: en_US
logo: # filename of a logo image that has been placed into your images directory

# Multi-site (translate)
languages: ["fr"]
#exclude_from_localizations: ["javascript", "images", "css"]
default_locale_in_subfolder: false

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Dr Geoffrey Pruvost
  avatar: bio-photo.jpg
  bio: "CTO / Directeur technique chez Diag n'Grow"
  email: 
  twitter: #username
  linkedin: geoffreypruvost
  github: geoffreyp
  orcid: 0000-0002-5049-5991
  researchgate: Geoffrey_Pruvost
  mendeley: #username
  google:
    plus: #username
    analytics:
    verify:
    scholar: 7fn66M0AAAAJ
  facebook: #username
  instagram: #username
  bing-verify:
  stackoverflow: 4227291/geoffrey-pruvost
  xing: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  disqus-shortname:

# The following adjust the accents for your site. If you would like to further edit colors, fonts, font sizes, etc.
# you may do so in _sass/variables.scss
highlight-color: '#CC0000'
lowlight-color: '#000'

  # NOTE: If you would like your site to be licensed under a creative commons license, uncomment the 'yes' next to the type of license you wish to use.
creative-commons:
  cc-by: #yes
  cc-by-nc: yes

#DO NOT EDIT BEYOND THIS POINT
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
